apiVersion: v1
kind: Service
metadata:
  name: vault-active-lb
  annotations: 
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    vault-active: "true"
  ports:
    - name: http
      port: 8200
    - name: server
      port: 8201
  loadBalancerIP: 10.10.51.14
