apiVersion: v1
kind: Service
metadata:
  name: secondary-vault-lb
  annotations: 
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: vault
  ports:
    - name: https
      port: 443
      targetPort: 8200
    - name: http
      port: 8200
    - name: server
      port: 8201
  loadBalancerIP: 10.10.51.13
