apiVersion: v1
kind: Service
metadata:
  name: vault-load-balancer
  annotations: 
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    app: vault
  ports:
    - name: http
      port: 8200
    - name: server
      port: 8201
  loadBalancerIP: 10.10.51.13
