apiVersion: v1
kind: Pod
metadata:
  name: alpinepod-1
  annotations:
    vault.hashicorp.com/tls-server-name: "vault-primary"
    vault.hashicorp.com/tls-secret: "vault"
    vault.hashicorp.com/ca-cert: "/vault/tls/ca.pem"
    vault.hashicorp.com/client-cert: "/vault/tls/vault.pem"
    vault.hashicorp.com/client-key: "/vault/tls/vault-key.pem"
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "devweb-app"
    vault.hashicorp.com/agent-inject-secret-credentials.txt: "secret/data/devwebapp/config"
    vault.hashicorp.com/agent-inject-template-credentials.txt: |
        {{- with secret "secret/data/devwebapp/config" -}}
        Username: {{ .Data.data.username }}: Password: {{ .Data.data.password }}
        {{- end }}
spec:
  serviceAccountName: internal-app
  containers:
  - name: alpinepod-1
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine

