---
apiVersion: v1
kind: Pod
metadata:
  name: devwebapp
  labels:
    app: devwebapp
  annotations:
    vault.hashicorp.com/tls-server-name: "vault-primary"
    vault.hashicorp.com/tls-secret: "vault"
    vault.hashicorp.com/ca-cert: "/vault/tls/ca.pem"
    vault.hashicorp.com/client-cert: "/vault/tls/vault.pem"
    vault.hashicorp.com/client-key: "/vault/tls/vault-key.pem"
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "devweb-app"
    vault.hashicorp.com/agent-inject-secret-credentials.txt: "secret/data/devwebapp/config"
spec:
  serviceAccountName: internal-app
  containers:
    - name: devwebapp
      image: jweissig/app:0.0.1
