apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-database
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.default:8200"
    vaultAddress: https://vault-primary.default.svc.cluster.local:8200
    vaultCACertPath: /mnt/tls/ca.pem
    vaultTLSClientCertPath: /mnt/tls/vault.pem
    vaultTLSClientKeyPath: /mnt/tls/vault-key.pem
    roleName: "database"
    objects: |
      - objectName: "db-password"
        secretPath: "secret/data/db-pass"
        secretKey: "password"
